replicaCount: 1

image:
  repository: pgpool/pgpool
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

postgres:
  main:
    host: cf-token-metadata-registry-pg
  replica:
    host: cf-token-metadata-registry-pg-repl
  credentials:
    secretName: postgres.cf-token-metadata-registry-pg.credentials.postgresql.acid.zalan.do
    usernameKey: username
    passwordKey: password


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoring:
  enabled: false
