apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  # name must start w/ teamId
  name: cf-token-metadata-registry-pg
  namespace: cf-token-metadata-registry
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  teamId: "cf"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    cardano: []
  databases:
    cf_token_metadata_registry: cardano
  postgresql:
    version: "15"
  enableLogicalBackup: true
