{{ if index .Values "cf-token-metadata-registry" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-token-metadata-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:cardano-foundation/cf-token-metadata-registry.git
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: deploy/cf-token-metadata-registry
    helm:
      parameters:
        - name: "domain"
          value: {{ .Values.domain }}
      {{- with index .Values "cf-token-metadata-registry" "values" }}
      values: |
{{ toYaml . | indent 8 }}
      {{- end }}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: cf-token-metadata-registry
    server: {{ .Values.spec.destination.server }}
{{ end }}
