FROM python:3.9-slim-bullseye

RUN apt update && apt upgrade
RUN apt install -y git build-essential libpq-dev
RUN git config --global pull.rebase false
WORKDIR /cf-gitsync-job/
COPY . /cf-gitsync-job/

RUN pip install -r "requirements.txt"

ENTRYPOINT ["/bin/bash", "/cf-gitsync-job/sync_from_github.sh"]
