version: "3.9"
services:
  db:
    image: "${DB_IMAGE_NAME}:${DB_IMAGE_TAG}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: "${DB_USER_SECRET}"
    volumes:
      - ./database/scripts/bootstrap_db.sql:/docker-entrypoint-initdb.d/bootstrap_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure