apiVersion: v1
kind: Service
metadata:
  name: {{ include "cf-pg-pool-ii.fullname" . }}
  labels:
    {{- include "cf-pg-pool-ii.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: db
      protocol: TCP
      name: db
  selector:
    {{- include "cf-pg-pool-ii.selectorLabels" . | nindent 4 }}
