blank_issues_enabled: true
contact_links:
  - name: Contributing guidelines
    url: https://github.com/cardano-foundation/cf-token-metadata-registry/blob/main/CONTRIBUTING.md
    about: Some rules & processes we honor.

  - name: Feature ideas
    url: https://github.com/cardano-foundation/cf-token-metadata-registry/discussions/categories/ideas
    about: Maybe someone else had the same or a similar idea already?

  - name: All issues
    url: https://github.com/cardano-foundation/cf-token-metadata-registry/issues
    about: Check whether your issue is not already covered here.