# Dockerfile used in compose to build and run project.
FROM maven:3-eclipse-temurin-25 AS builder

ADD . /app
WORKDIR /app
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre

COPY --from=builder /app/api/target/*.jar /app/app.jar
WORKDIR /app
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar app.jar"]
