name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout badges branch
        uses: actions/checkout@v6
        with:
          ref: badges
          path: badges

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn --batch-mode clean verify

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          jacoco-csv-file: api/target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push badges
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain ./*.svg` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add ./*.svg
            git commit -m "Autogenerated JaCoCo coverage badge" ./*.svg
            git push
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: api/target/site/jacoco/

      - name: Upload API JAR
        uses: actions/upload-artifact@v4
        with:
          name: api-jar
          path: api/target/api-*.jar

      - name: Upload Job JAR
        uses: actions/upload-artifact@v4
        with:
          name: job-jar
          path: job/target/job-*.jar
