name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  java-build:
    uses: ./.github/workflows/build.yaml

  integration-test-jar:
    needs: java-build
    uses: ./.github/workflows/integration-tests.yml
    with:
      target: jar

  docker-build-jvm:
    needs: java-build
    uses: ./.github/workflows/docker-build.yaml
    with:
      app: api
      variant: jvm

  integration-test-docker-jvm:
    needs: docker-build-jvm
    uses: ./.github/workflows/integration-tests.yml
    with:
      target: docker-jvm
      image-tag: ${{ needs.docker-build-jvm.outputs.image-tag }}
