name: Build and Publish Docker images

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  java-build:
    uses: ./.github/workflows/build.yaml

  docker-api-jvm:
    needs: java-build
    uses: ./.github/workflows/docker-build.yaml
    with:
      app: api
      variant: jvm
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-api-native:
    needs: java-build
    uses: ./.github/workflows/docker-build.yaml
    with:
      app: api
      variant: native
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-job:
    needs: java-build
    uses: ./.github/workflows/docker-build.yaml
    with:
      app: job
      variant: jvm
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
